[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/numerique/"
to = "/articles/numerique/"

[[redirects]]
from = "/agenda/archives/"
to = "/seminaires/archives/"

[[redirects]]
from = "/equipe/yannick-bosc/actualites/"
to = "/equipe/yannick-bosc/articles/"

[[redirects]]
from = "/actualites/etat/"
to = "/articles/etat/"

[[redirects]]
from = "/actualites/sante/"
to = "/articles/sante/"

[[redirects]]
from = "/articles/2024-04-25-la-reconnaissance-dun-possible-droit-de-deambuler/"
to = "/articles/2024-05-22-la-reconnaissance-dun-possible-droit-de-deambuler/"

[[redirects]]
from = "/actualites/espaces/"
to = "/articles/espaces/"

[[redirects]]
from = "/actualites/2024-04-22-linternet-que-nous-aurions-pu-avoir/"
to = "/articles/2024-05-22-linternet-que-nous-aurions-pu-avoir/"

[[redirects]]
from = "/articles/2024-04-25-editorial-une-voix-pour-les-communs/"
to = "/articles/2024-05-22-editorial-une-voix-pour-les-communs/"

[[redirects]]
from = "/actualites/interet-general/"
to = "/articles/interet-general/"

[[redirects]]
from = "/equipe/sebastien-broca/actualites/"
to = "/equipe/sebastien-broca/articles/"

[[redirects]]
from = "/les-fondateurs/"
to = "/a-propos/les-fondateurs/"

[[redirects]]
from = "/articles/2024-05-22-defendre-nos-tiers-lieux-entretien-avec-antoine-burret-et-yoann-duriaux/"
to = "/articles/2024-05-22-defendre-nos-tiers-lieux/"

[[redirects]]
from = "/equipe/christopher-kelty/actualites/"
to = "/equipe/christopher-kelty/articles/"

[[redirects]]
from = "/l-association/"
to = "/a-propos/"

[[redirects]]
from = "/comite-de-redaction/"
to = "/a-propos/comite-de-redaction/"

[[redirects]]
from = "/actualites/"
to = "/articles/"

[[redirects]]
from = "/actualites/ecologie/"
to = "/articles/ecologie/"

[[redirects]]
from = "/articles/2024-04-25-interet-general-propriete-et-republique-1/"
to = "/articles/2024-05-22-interet-general-propriete-et-republique-1/"

[[redirects]]
from = "/articles/2024-05-04-defendre-nos-tiers-lieux-entretien-avec-antoine-burret-et-yoann-duriaux/"
to = "/articles/2024-05-22-defendre-nos-tiers-lieux/"

[[redirects]]
from = "/agenda/"
to = "/seminaires/"

[[redirects]]
from = "/articles/2024-04-22-linternet-que-nous-aurions-pu-avoir/"
to = "/articles/2024-05-22-linternet-que-nous-aurions-pu-avoir/"

[[redirects]]
from = "/charte-contributeurs/"
to = "/a-propos/charte-contributeurs/"

